FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY tasks.py .
COPY celeryconfig.py .
COPY config.py . 
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]